[SiliconFlow]
enable = true                           # 是否启用此功能
handle_all_messages = false               # 是否处理所有消息（不需要命令前缀）
api-key = ""                            # 硅基流动API密钥，必填
base-url = "https://api.siliconflow.cn/v1"  # 硅基流动API地址

# 模型配置
default-model = "Qwen/QwQ-32B"          # 默认使用的模型
available-models = [                    # 可用模型列表
    "Qwen/QwQ-32B",
    "Qwen/Qwen2.5-72B-Instruct",
    "Qwen/Qwen2.5-32B-Instruct",
    "Qwen/Qwen2.5-14B-Instruct",
    "Qwen/Qwen2.5-7B-Instruct",
    "THUDM/glm-4-9b-chat",
    "deepseek-ai/DeepSeek-R1"
]

# 命令配置
commands = ["硅基", "sf", "SiliconFlow"]  # 触发插件的命令

# Http代理设置
# 格式: http://用户名:密码@代理地址:代理端口
# 例如：http://127.0.0.1:7890
http-proxy = ""

# 高级设置
max_tokens = 4096                       # 最大token数
temperature = 0.7                       # 温度参数
top_p = 0.7                             # Top-p采样
top_k = 50                              # Top-k采样
frequency_penalty = 0.5                 # 频率惩罚
